version: '3.3'
services:
  holigo-faq-service:
    image: holigo/holigo-faq-service:1.2.0
    ports:
      - 8101:8101
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-faq-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-faq-service"}}'
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 512M
  holigo-live-chat-service:
    image: holigo/holigo-live-chat-service:1.0.5
    ports:
      - 8112:8112
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-live-chat-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-live-chat-service"}}'
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 512M
