version: '3.3'
services:
  holigo-faq-service:
    image: holigo/holigo-faq-service:1.0.1
    ports:
      - 8101:8101
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_APPLICATION_JSON: '{"eureka":{"client":{"serviceUrl":{"defaultZone":"http://netflix:eureka@10.1.1.15:8761/eureka/"},"region":"default","register-with-eureka":true},"instance":{"preferIpAddress":false,"hostName":"holigo-faq-service"}},"spring":{"cloud":{"config":{"discovery":{"enabled":true,"serviceId":"holigo-config-server"},"failFast":true,"username":"","password":""}}},"application":{"name":"holigo-faq-service"}}'
    deploy:
      replicas: 1